version: '3.7'

services:
  nginx:
    image: nginx
    container_name: analytics_nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
    volumes:
      - ./static/favicon.ico:/usr/projects/go-analytics/static/favicon.ico
      - ./nginx/letsencrypt:/etc/letsencrypt
      - ./nginx:/etc/nginx/conf.d

  db:
    container_name: analytics_db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - /usr/projects/psql/analytics_db:/var/lib/psql/data
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB

  redis:
    container_name: analytics_redis
    image: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: always
    ports:
      - 6379:6379

  web:
    build: .
    container_name: analytics_web
    image: analytics_image
    command: bash -c "go build -o web src/main.go src/structures.go && ./web"
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - 8080:8080
    volumes:
      - .:/usr/projects/go-analytics
