version: '3.7'

services:
  nginx:
    image: nginx
    container_name: logging_nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
    volumes:
      - ./static/favicon.ico:/usr/projects/go-logging/static/favicon.ico
      - ./nginx/letsencrypt:/etc/letsencrypt
      - ./nginx:/etc/nginx/conf.d

  db:
    container_name: logging_db
    image: postgres
    restart: always
    ports:
      - 6432:5432
    volumes:
      - /usr/projects/psql/logging_db:/var/lib/psql/data
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB

  web:
    build: .
    container_name: logging_web
    image: logging_image
    command: bash -c "go build -o web src/*.go && ./web"
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
    volumes:
      - .:/usr/projects/go-logging
